#!/usr/bin/env bash
# Translations: English and Russian
# Usage: choose_language fills global T[] with the selected language strings.

declare -A T

declare -A _EN
_EN=(
  # ── Generic UI ─────────────────────────────────────────────────────────────
  [title]="MrCerber Server Tools"
  [subtitle]="Ubuntu / Debian  |  Run as root"
  [select_lang]="Choose language"
  [confirm_yes]="Yes"
  [confirm_no]="No"
  [press_enter]="Press Enter to continue..."
  [back]="Back"
  [exit]="🚪 Exit"
  [invalid_choice]="Invalid choice."
  [cannot_be_empty]="Cannot be empty."
  [done]="Done."

  # ── Errors ─────────────────────────────────────────────────────────────────
  [err_backup_failed]="Backup failed — aborting."
  [err_download_failed]="Download failed"
  [err_invalid_port]="Invalid port. Must be 1–65535."
  [err_invalid_ip]="Invalid IPv4 or CIDR format."
  [err_invalid_size]="Invalid size. Examples: 1G, 2G, 512M"
  [err_sshd_invalid]="sshd config is invalid — backup restored. No reload performed."

  # ── OS / Internet ──────────────────────────────────────────────────────────
  [os_not_ubuntu]="Designed for Ubuntu/Debian."
  [os_continue]="Continue anyway?"
  [no_internet]="No internet connectivity detected."

  # ── Menu sections ──────────────────────────────────────────────────────────
  [sec_quick]="⚡ Quick Start"
  [sec_system]="🖥️  System"
  [sec_users]="👤 Users"
  [sec_security]="🛡️  Security"
  [sec_appearance]="🎨 Appearance"
  [sec_services]="📦 Services"
  [sec_utils]="🔧 Utilities"

  # ── Main menu items ────────────────────────────────────────────────────────
  [m_alias]="🔗 Create launcher alias (mrc-tools)"
  [m_full_setup]="🚀 Full base setup"
  [m_update]="⬆️  Update / upgrade only"
  [m_packages]="📦 Install base packages"
  [m_autoupdates]="🔁 Enable auto-updates"
  [m_sudo_user]="👤 Create sudo user"
  [m_swap]="💾 Setup swap"
  [m_motd_install]="🎨 Install custom MOTD"
  [m_motd_restore]="↩️  Restore default MOTD"
  [m_motd_preview]="👁️  Preview MOTD"
  [m_ssh]="🔑 SSH settings >"
  [m_ufw]="🧱 UFW firewall >"
  [m_fail2ban]="🔒 Fail2ban >"
  [m_hardening]="⚙️  Kernel hardening"
  [m_docker]="🐳 Install Docker"
  [m_1panel]="📊 Install 1Panel"
  [m_aliases]="✨ Install shell aliases"
  [m_apt_clean]="🧹 APT cleanup"
  [m_cron]="⏰ Auto-reboot cron"
  [m_log]="📋 Show action log"
  [m_scripts]="📜 Scripts >"

  # ── Section descriptions ───────────────────────────────────────────────────
  [d_sec_quick]="Full base setup and launcher alias"
  [d_sec_system]="Update, install packages, enable auto-updates, configure swap"
  [d_sec_users]="Create sudo user with optional SSH key"
  [d_sec_security]="SSH hardening, UFW firewall, Fail2ban, kernel sysctl"
  [d_sec_appearance]="Custom MOTD install, restore, and preview"
  [d_sec_services]="Install Docker and 1Panel management panel"
  [d_sec_utils]="Aliases, APT cleanup, auto-reboot cron, utility scripts, action log"

  # ── Item descriptions ──────────────────────────────────────────────────────
  [d_full_setup]="Update system, install base packages, and enable auto-updates in one step"
  [d_alias]="Add 'mrc-tools' command to /usr/local/bin for quick access anywhere"
  [d_update]="Run apt-get update && upgrade — updates without installing new packages"
  [d_packages]="Install curl, git, htop, btop, jq, ufw, fail2ban, and common essentials"
  [d_autoupdates]="Configure unattended-upgrades for automatic security updates"
  [d_sudo_user]="Create a new user, add to sudo group, optionally install SSH public key"
  [d_swap]="Create /swapfile swap space, set swappiness=10, persist in /etc/fstab"
  [d_ssh]="Manage SSH port, disable password auth, restrict root login"
  [d_ufw]="Configure UFW firewall rules, set defaults, enable or disable"
  [d_fail2ban]="Install and configure Fail2ban for SSH brute-force protection"
  [d_hardening]="Apply sysctl hardening: SYN cookies, anti-spoof, ICMP redirect protection"
  [d_motd_install]="Replace default MOTD with custom system stats display (99-mrcerber)"
  [d_motd_restore]="Re-enable default Ubuntu/Debian MOTD scripts"
  [d_motd_preview]="Preview MOTD output: run-parts /etc/update-motd.d"
  [d_docker]="Download and run the official Docker install script (get.docker.com)"
  [d_1panel]="Download and run the 1Panel web-based server management installer"
  [d_aliases]="Add bench, geoip shortcut aliases to /root/.bashrc"
  [d_apt_clean]="Run apt-get autoremove + clean to free up disk space"
  [d_cron]="Install/manage auto-reboot cron (reboots only when kernel update pending)"
  [d_scripts]="Run utility scripts: Cloudflare DNS manager, enable TCP BBR"
  [d_log]="View the last entries from the bootstrap action log"

  # ── SSH submenu ────────────────────────────────────────────────────────────
  [ssh_menu_title]="SSH Hardening"
  [ssh_m_status]="Status"
  [ssh_m_add_key]="Add SSH public key"
  [ssh_m_disable_pass]="Disable password auth"
  [ssh_m_restrict_root]="Restrict root login"
  [ssh_m_change_port]="Change SSH port"
  [ssh_status_title]="Current SSH settings"
  [ssh_port]="Port:"
  [ssh_pass_auth]="PasswordAuthentication:"
  [ssh_root_login]="PermitRootLogin:"
  [ssh_printlastlog]="PrintLastLog:"
  [ssh_add_key_prompt]="Paste SSH public key (ssh-ed25519 / ssh-rsa / ecdsa-...):"
  [ssh_add_key_done]="SSH public key added to /root/.ssh/authorized_keys."
  [ssh_key_already_exists]="This key is already in authorized_keys."
  [ssh_no_keys_abort]="BLOCKED: No SSH keys found in /root/.ssh/authorized_keys. Add a key first — otherwise disabling password auth will lock you out completely."
  [ssh_add_key_hint]="Use 'Add SSH public key' from this menu to add your key first."
  [ssh_keys_found]="Found %s authorized key(s) in /root/.ssh/authorized_keys."
  [ssh_disable_pass_warn]="This will lock out ALL password-based SSH logins on this server."
  [ssh_disable_pass_confirm]="Disable password authentication?"
  [ssh_disable_pass_done]="Password authentication disabled. Key-based login only."
  [ssh_restrict_root_info]="Root can still log in with SSH keys; password login for root will be blocked."
  [ssh_restrict_root_done]="Root password login disabled (key-based root login still works)."
  [ssh_port_prompt]="New SSH port (1–65535):"
  [ssh_port_confirm]="Change SSH port to %s?"
  [ssh_port_done]="SSH port changed to %s. Reconnect on the new port."
  [ssh_port_ufw_added]="UFW rule for port %s/tcp added automatically."

  # ── UFW submenu ────────────────────────────────────────────────────────────
  [ufw_menu_title]="UFW Firewall"
  [ufw_m_status]="Status"
  [ufw_m_defaults]="Apply defaults (deny in / allow out)"
  [ufw_m_ssh]="Allow SSH (22/tcp)"
  [ufw_m_http]="Allow HTTP + HTTPS (80, 443)"
  [ufw_m_custom]="Allow custom port"
  [ufw_m_from_ip]="Allow from IP/CIDR"
  [ufw_m_delete]="Delete rule by number"
  [ufw_m_enable]="Enable UFW"
  [ufw_m_disable]="Disable UFW"
  [ufw_m_reset]="Reset UFW (removes all rules!)"
  [ufw_port_prompt]="Port (e.g. 8443):"
  [ufw_proto_prompt]="Protocol — tcp / udp / both (default: tcp):"
  [ufw_ip_prompt]="Source IP or CIDR (e.g. 1.2.3.4 or 1.2.3.0/24):"
  [ufw_port2_prompt]="Port to open (1–65535):"
  [ufw_delete_title]="Current UFW rules:"
  [ufw_delete_prompt]="Rule number to delete:"
  [ufw_delete_confirm]="Delete rule #%s?"
  [ufw_delete_done]="Rule deleted."
  [ufw_delete_fail]="Failed to delete rule — the rule number may no longer exist."
  [ufw_reset_confirm]="This will reset UFW and remove ALL rules. Continue?"
  [ufw_defaults_done]="Defaults applied: deny incoming / allow outgoing."

  # ── Fail2ban submenu ───────────────────────────────────────────────────────
  [f2b_menu_title]="Fail2ban"
  [f2b_m_install]="Install + enable"
  [f2b_m_jail]="Configure SSH jail"
  [f2b_m_status]="Status"
  [f2b_m_unban]="Unban IP"
  [f2b_not_installed]="Fail2ban not installed. Use 'Install + enable' first."
  [f2b_unban_prompt]="IP address to unban:"
  [f2b_done]="Fail2ban installed and enabled."
  [f2b_jail_done]="jail.local written and fail2ban restarted."
  [f2b_restart_failed]="Fail2ban restart failed. Ensure it is installed and enabled."

  # ── System ─────────────────────────────────────────────────────────────────
  [sys_updating]="Updating package lists..."
  [sys_upgrading]="Upgrading installed packages..."
  [sys_installing_base]="Installing base packages..."
  [sys_upgrade_done]="System updated and upgraded successfully."
  [sys_packages_done]="Base packages installed successfully."
  [sys_auto_updates_done]="Unattended upgrades enabled."
  [swap_exists]="Swap is already configured:"
  [swap_replace_confirm]="Replace existing swap?"
  [swap_size_prompt]="Swap size (e.g. 1G, 2G, 512M):"
  [swap_create_confirm]="Create %s swapfile at /swapfile?"
  [swap_fallocate_fail]="fallocate failed (btrfs?); falling back to dd..."
  [swap_create_fail]="Swapfile creation failed. Check the log for details. Common causes: insufficient disk space, container virtualization (OpenVZ/LXC), or filesystem limitations."
  [swap_done]="Swap configured: %s at /swapfile (swappiness=10)"
  [user_prompt]="New username:"
  [user_invalid]="Invalid username. Use lowercase letters, digits, underscores, hyphens (max 32 chars)."
  [user_exists]="User '%s' already exists."
  [user_confirm]="Create user '%s' and add to sudo?"
  [user_done]="User '%s' created and added to sudo."
  [user_ssh_key_prompt]="SSH public key for %s (leave blank to skip):"
  [user_ssh_key_invalid]="Invalid SSH public key format."
  [user_ssh_key_done]="SSH public key installed for '%s'."
  [alias_exists]="already exists, skipping."
  [alias_added]="added."
  [alias_reload_note]="NOTE: Run 'source ~/.bashrc' or reconnect via SSH to apply aliases."
  [apt_before]="Cache before cleanup: %s"
  [apt_after]="Cache after cleanup: %s"
  [cron_active]="Auto-reboot cron is currently active:"
  [cron_reconfigure]="Reconfigure?"
  [cron_disable_confirm]="Disable auto-reboot cron?"
  [cron_disabled]="Auto-reboot cron removed."
  [cron_install_confirm]="Install auto-reboot cron? (runs hourly, reboots only if kernel update pending)"
  [cron_done]="Auto-reboot cron installed."
  [hardening_exists]="Kernel hardening already applied."
  [hardening_reapply]="Re-apply / overwrite?"
  [hardening_done]="Kernel hardening applied."
  [full_setup_done]="Setup Complete"
  [full_setup_packages]="Packages updated:"
  [full_setup_base]="Base packages:"
  [full_setup_updates]="Auto-updates:"
  [full_setup_duration]="Duration:"

  # ── MOTD ───────────────────────────────────────────────────────────────────
  [motd_downloading]="Custom MOTD files not found locally; downloading..."
  [motd_installed]="Custom MOTD installed."
  [motd_restored]="Default MOTD restored."
  [motd_preview_title]="MOTD Preview"
  [motd_no_curl_wget]="Missing custom files and neither curl nor wget is available."

  # ── Log ────────────────────────────────────────────────────────────────────
  [log_empty]="No log file found."

  # ── Docker ─────────────────────────────────────────────────────────────────
  [docker_installed]="Docker is already installed: %s"
  [docker_reinstall]="Re-install anyway?"
  [docker_warn]="This will download and run the official Docker install script as root."
  [docker_sha256]="SHA256 of installer: %s"
  [docker_confirm]="Run Docker install script?"
  [docker_downloading]="Downloading Docker installer..."
  [docker_done]="Docker installed: %s"
  [docker_install_fail]="Docker install script failed. Check the log for details."
  [1panel_warn]="This will download and run the 1Panel installer script as root."
  [1panel_confirm]="Run 1Panel install script?"
  [1panel_downloading]="Downloading 1Panel installer..."

  # ── Scripts submenu ────────────────────────────────────────────────────────
  [scripts_menu_title]="Utility Scripts"
  [scripts_m_cf]="Cloudflare DNS Manager"
  [scripts_m_bbr]="Enable TCP BBR"
  [scripts_downloading]="Script not found locally; downloading from GitHub..."
)

declare -A _RU
_RU=(
  [title]="Инструменты сервера MrCerber"
  [subtitle]="Ubuntu / Debian  |  Запуск от root"
  [select_lang]="Выберите язык"
  [confirm_yes]="Да"
  [confirm_no]="Нет"
  [press_enter]="Нажмите Enter для продолжения..."
  [back]="Назад"
  [exit]="🚪 Выход"
  [invalid_choice]="Неверный выбор."
  [cannot_be_empty]="Не может быть пустым."
  [done]="Готово."

  [err_backup_failed]="Ошибка резервной копии — прерывание."
  [err_download_failed]="Ошибка загрузки"
  [err_invalid_port]="Неверный порт. Должен быть от 1 до 65535."
  [err_invalid_ip]="Неверный формат IPv4 или CIDR."
  [err_invalid_size]="Неверный формат. Примеры: 1G, 2G, 512M"
  [err_sshd_invalid]="Конфиг sshd невалиден — резервная копия восстановлена."

  [os_not_ubuntu]="Скрипт предназначен для Ubuntu/Debian."
  [os_continue]="Продолжить всё равно?"
  [no_internet]="Нет подключения к интернету."

  [sec_quick]="⚡ Быстрый старт"
  [sec_system]="🖥️  Система"
  [sec_users]="👤 Пользователи"
  [sec_security]="🛡️  Безопасность"
  [sec_appearance]="🎨 Оформление"
  [sec_services]="📦 Сервисы"
  [sec_utils]="🔧 Утилиты"

  [m_alias]="🔗 Создать alias (mrc-tools)"
  [m_full_setup]="🚀 Полная установка"
  [m_update]="⬆️  Обновить систему"
  [m_packages]="📦 Установить базовые пакеты"
  [m_autoupdates]="🔁 Включить авто-обновления"
  [m_sudo_user]="👤 Создать sudo пользователя"
  [m_swap]="💾 Настроить swap"
  [m_motd_install]="🎨 Установить кастомный MOTD"
  [m_motd_restore]="↩️  Восстановить MOTD"
  [m_motd_preview]="👁️  Предпросмотр MOTD"
  [m_ssh]="🔑 Настройки SSH >"
  [m_ufw]="🧱 Фаервол UFW >"
  [m_fail2ban]="🔒 Fail2ban >"
  [m_hardening]="⚙️  Харденинг ядра"
  [m_docker]="🐳 Установить Docker"
  [m_1panel]="📊 Установить 1Panel"
  [m_aliases]="✨ Установить aliases"
  [m_apt_clean]="🧹 Очистка APT"
  [m_cron]="⏰ Крон авто-перезагрузки"
  [m_log]="📋 Показать лог"
  [m_scripts]="📜 Скрипты >"

  # ── Описания секций ────────────────────────────────────────────────────────
  [d_sec_quick]="Полная установка системы и создание alias mrc-tools"
  [d_sec_system]="Обновление, пакеты, авто-обновления, настройка swap"
  [d_sec_users]="Создание sudo-пользователя с опциональным SSH-ключом"
  [d_sec_security]="Настройки SSH, UFW, Fail2ban, харденинг ядра"
  [d_sec_appearance]="Установка, восстановление и предпросмотр MOTD"
  [d_sec_services]="Установка Docker и панели управления 1Panel"
  [d_sec_utils]="Алиасы, очистка APT, крон авто-перезагрузки, утилиты, лог"

  # ── Описания пунктов ───────────────────────────────────────────────────────
  [d_full_setup]="Обновить систему, установить базовые пакеты и авто-обновления за один шаг"
  [d_alias]="Добавить команду 'mrc-tools' в /usr/local/bin для быстрого запуска"
  [d_update]="Запустить apt-get update && upgrade — без установки новых пакетов"
  [d_packages]="Установить curl, git, htop, btop, jq, ufw, fail2ban и другие утилиты"
  [d_autoupdates]="Настроить unattended-upgrades для автоматических обновлений безопасности"
  [d_sudo_user]="Создать пользователя, добавить в sudo, опционально установить SSH-ключ"
  [d_swap]="Создать /swapfile, установить swappiness=10, добавить в /etc/fstab"
  [d_ssh]="Управление портом SSH, входом по паролю и root-доступом"
  [d_ufw]="Настройка правил UFW, политик по умолчанию и статуса"
  [d_fail2ban]="Установка и настройка Fail2ban для защиты SSH от брутфорса"
  [d_hardening]="Применить sysctl харденинг: SYN cookies, защита от спуфинга"
  [d_motd_install]="Заменить стандартный MOTD на кастомный с системной статистикой"
  [d_motd_restore]="Восстановить стандартные скрипты MOTD Ubuntu/Debian"
  [d_motd_preview]="Посмотреть как выглядит MOTD: run-parts /etc/update-motd.d"
  [d_docker]="Скачать и запустить официальный скрипт установки Docker"
  [d_1panel]="Скачать и запустить установщик 1Panel"
  [d_aliases]="Добавить алиасы bench, geoip в /root/.bashrc"
  [d_apt_clean]="Запустить apt-get autoremove + clean для освобождения диска"
  [d_cron]="Установить/управлять авто-перезагрузкой по крону"
  [d_scripts]="Запустить утилиты: Cloudflare DNS manager, включить TCP BBR"
  [d_log]="Просмотреть записи из лога действий bootstrap"

  [ssh_menu_title]="Настройки SSH"
  [ssh_m_status]="Статус"
  [ssh_m_add_key]="Добавить SSH публичный ключ"
  [ssh_m_disable_pass]="Отключить вход по паролю"
  [ssh_m_restrict_root]="Ограничить root-вход"
  [ssh_m_change_port]="Изменить порт SSH"
  [ssh_status_title]="Текущие настройки SSH"
  [ssh_port]="Порт:"
  [ssh_pass_auth]="Аутентификация по паролю:"
  [ssh_root_login]="Вход под root:"
  [ssh_printlastlog]="Вывод последнего входа:"
  [ssh_add_key_prompt]="Вставьте SSH публичный ключ (ssh-ed25519 / ssh-rsa / ecdsa-...):"
  [ssh_add_key_done]="SSH публичный ключ добавлен в /root/.ssh/authorized_keys."
  [ssh_key_already_exists]="Этот ключ уже есть в authorized_keys."
  [ssh_no_keys_abort]="ЗАБЛОКИРОВАНО: в /root/.ssh/authorized_keys нет ни одного ключа. Сначала добавьте ключ — иначе отключение пароля полностью закроет доступ к серверу."
  [ssh_add_key_hint]="Используйте пункт 'Добавить SSH публичный ключ' в этом меню."
  [ssh_keys_found]="Найдено авторизованных ключей: %s в /root/.ssh/authorized_keys."
  [ssh_disable_pass_warn]="Это закроет вход по паролю для ВСЕХ пользователей на этом сервере."
  [ssh_disable_pass_confirm]="Отключить аутентификацию по паролю?"
  [ssh_disable_pass_done]="Аутентификация по паролю отключена. Только вход по ключу."
  [ssh_restrict_root_info]="Root сможет заходить по ключу, но не по паролю."
  [ssh_restrict_root_done]="Вход root по паролю запрещён (вход по ключу остаётся)."
  [ssh_port_prompt]="Новый порт SSH (1–65535):"
  [ssh_port_confirm]="Изменить порт SSH на %s?"
  [ssh_port_done]="Порт SSH изменён на %s. Переподключитесь по новому порту."
  [ssh_port_ufw_added]="Правило UFW для порта %s/tcp добавлено автоматически."

  [ufw_menu_title]="Фаервол UFW"
  [ufw_m_status]="Статус"
  [ufw_m_defaults]="Применить политики (запрет входящих / разрешение исходящих)"
  [ufw_m_ssh]="Разрешить SSH (22/tcp)"
  [ufw_m_http]="Разрешить HTTP + HTTPS (80, 443)"
  [ufw_m_custom]="Открыть произвольный порт"
  [ufw_m_from_ip]="Разрешить с IP/CIDR"
  [ufw_m_delete]="Удалить правило по номеру"
  [ufw_m_enable]="Включить UFW"
  [ufw_m_disable]="Выключить UFW"
  [ufw_m_reset]="Сбросить UFW (удалит все правила!)"
  [ufw_port_prompt]="Порт (например, 8443):"
  [ufw_proto_prompt]="Протокол — tcp / udp / both (по умолчанию: tcp):"
  [ufw_ip_prompt]="IP или CIDR источника (например, 1.2.3.4 или 1.2.3.0/24):"
  [ufw_port2_prompt]="Порт для открытия (1–65535):"
  [ufw_delete_title]="Текущие правила UFW:"
  [ufw_delete_prompt]="Номер правила для удаления:"
  [ufw_delete_confirm]="Удалить правило #%s?"
  [ufw_delete_done]="Правило удалено."
  [ufw_delete_fail]="Не удалось удалить правило — такого номера больше нет."
  [ufw_reset_confirm]="Это сбросит UFW и удалит ВСЕ правила. Продолжить?"
  [ufw_defaults_done]="Политики применены: запрет входящих / разрешение исходящих."

  [f2b_menu_title]="Fail2ban"
  [f2b_m_install]="Установить + включить"
  [f2b_m_jail]="Настроить SSH jail"
  [f2b_m_status]="Статус"
  [f2b_m_unban]="Разбанить IP"
  [f2b_not_installed]="Fail2ban не установлен. Сначала используйте 'Установить + включить'."
  [f2b_unban_prompt]="IP-адрес для разбана:"
  [f2b_done]="Fail2ban установлен и включён."
  [f2b_jail_done]="jail.local записан, fail2ban перезапущен."
  [f2b_restart_failed]="Перезапуск fail2ban не удался. Убедитесь, что он установлен."

  [sys_updating]="Обновление списков пакетов..."
  [sys_upgrading]="Обновление установленных пакетов..."
  [sys_installing_base]="Установка базовых пакетов..."
  [sys_upgrade_done]="Система успешно обновлена."
  [sys_packages_done]="Базовые пакеты успешно установлены."
  [sys_auto_updates_done]="Авто-обновления включены."
  [swap_exists]="Swap уже настроен:"
  [swap_replace_confirm]="Заменить существующий swap?"
  [swap_size_prompt]="Размер swap (например, 1G, 2G, 512M):"
  [swap_create_confirm]="Создать swapfile размером %s в /swapfile?"
  [swap_fallocate_fail]="fallocate не сработал (btrfs?); используется dd..."
  [swap_create_fail]="Не удалось создать swapfile. Подробности в логе. Причины: нехватка места, контейнерная виртуализация (OpenVZ/LXC), ограничения файловой системы."
  [swap_done]="Swap настроен: %s в /swapfile (swappiness=10)"
  [user_prompt]="Имя нового пользователя:"
  [user_invalid]="Неверное имя. Допустимы: строчные буквы, цифры, подчёркивания, дефисы (макс. 32 символа)."
  [user_exists]="Пользователь '%s' уже существует."
  [user_confirm]="Создать пользователя '%s' и добавить в sudo?"
  [user_done]="Пользователь '%s' создан и добавлен в sudo."
  [user_ssh_key_prompt]="SSH публичный ключ для %s (оставьте пустым, чтобы пропустить):"
  [user_ssh_key_invalid]="Неверный формат SSH публичного ключа."
  [user_ssh_key_done]="SSH ключ установлен для '%s'."
  [alias_exists]="уже существует, пропускаю."
  [alias_added]="добавлен."
  [alias_reload_note]="ВАЖНО: Выполните 'source ~/.bashrc' или переподключитесь по SSH для применения."
  [apt_before]="Кэш до очистки: %s"
  [apt_after]="Кэш после очистки: %s"
  [cron_active]="Крон авто-перезагрузки активен:"
  [cron_reconfigure]="Перенастроить?"
  [cron_disable_confirm]="Отключить крон авто-перезагрузки?"
  [cron_disabled]="Крон авто-перезагрузки удалён."
  [cron_install_confirm]="Установить крон авто-перезагрузки? (запускается каждый час, перезагружает только при ожидающих обновлениях ядра)"
  [cron_done]="Крон авто-перезагрузки установлен."
  [hardening_exists]="Харденинг ядра уже применён."
  [hardening_reapply]="Применить заново / перезаписать?"
  [hardening_done]="Харденинг ядра применён."
  [full_setup_done]="Установка завершена"
  [full_setup_packages]="Пакеты обновлены:"
  [full_setup_base]="Базовые пакеты:"
  [full_setup_updates]="Авто-обновления:"
  [full_setup_duration]="Время:"

  [motd_downloading]="Файлы MOTD не найдены локально; загрузка..."
  [motd_installed]="Кастомный MOTD установлен."
  [motd_restored]="MOTD по умолчанию восстановлен."
  [motd_preview_title]="Предпросмотр MOTD"
  [motd_no_curl_wget]="Файлы MOTD отсутствуют, и нет curl или wget."

  [log_empty]="Файл лога не найден."

  [docker_installed]="Docker уже установлен: %s"
  [docker_reinstall]="Переустановить?"
  [docker_warn]="Будет скачан и выполнен официальный скрипт установки Docker от root."
  [docker_sha256]="SHA256 установщика: %s"
  [docker_confirm]="Запустить скрипт установки Docker?"
  [docker_downloading]="Скачивание установщика Docker..."
  [docker_done]="Docker установлен: %s"
  [docker_install_fail]="Скрипт установки Docker завершился с ошибкой. Подробности в логе."
  [1panel_warn]="Будет скачан и выполнен скрипт установки 1Panel от root."
  [1panel_confirm]="Запустить скрипт установки 1Panel?"
  [1panel_downloading]="Скачивание установщика 1Panel..."

  [scripts_menu_title]="Утилиты"
  [scripts_m_cf]="Cloudflare DNS Manager"
  [scripts_m_bbr]="Включить TCP BBR"
  [scripts_downloading]="Скрипт не найден локально; загрузка с GitHub..."
)

choose_language() {
  local lang
  lang=$(gum choose --header="Language / Язык" "English" "Русский") || lang="English"

  local -n _src
  if [[ "$lang" == "English" ]]; then
    _src=_EN
  else
    _src=_RU
  fi

  local k
  for k in "${!_src[@]}"; do
    T["$k"]="${_src[$k]}"
  done
}
