#!/usr/bin/env bash
# Translations: English and Russian
# Usage: choose_language fills global T[] with the selected language strings.

declare -A T

declare -A _EN
_EN=(
  # ── Generic UI ─────────────────────────────────────────────────────────────
  [title]="MrCerber Server Tools"
  [subtitle]="Ubuntu / Debian  |  Run as root"
  [select_lang]="Choose language"
  [confirm_yes]="Yes"
  [confirm_no]="No"
  [press_enter]="Press Enter to continue..."
  [back]="Back"
  [exit]="Exit"
  [invalid_choice]="Invalid choice."
  [cannot_be_empty]="Cannot be empty."
  [done]="Done."

  # ── Errors ─────────────────────────────────────────────────────────────────
  [err_backup_failed]="Backup failed — aborting."
  [err_download_failed]="Download failed"
  [err_invalid_port]="Invalid port. Must be 1–65535."
  [err_invalid_ip]="Invalid IPv4 or CIDR format."
  [err_invalid_size]="Invalid size. Examples: 1G, 2G, 512M"
  [err_sshd_invalid]="sshd config is invalid — backup restored. No reload performed."

  # ── OS / Internet ──────────────────────────────────────────────────────────
  [os_not_ubuntu]="Designed for Ubuntu/Debian."
  [os_continue]="Continue anyway?"
  [no_internet]="No internet connectivity detected."

  # ── Menu sections ──────────────────────────────────────────────────────────
  [sec_quick]="Quick Setup"
  [sec_system]="System"
  [sec_motd_ssh]="MOTD & SSH"
  [sec_security]="Security"
  [sec_panels]="Panels"
  [sec_extras]="Extras"
  [sec_scripts]="Scripts"

  # ── Main menu items ────────────────────────────────────────────────────────
  [m_alias]="Create launcher alias (mrc-tools)"
  [m_full_setup]="Full base setup"
  [m_update]="Update / upgrade only"
  [m_packages]="Install base packages"
  [m_autoupdates]="Enable auto-updates"
  [m_sudo_user]="Create sudo user"
  [m_swap]="Setup swap"
  [m_motd_install]="Install custom MOTD"
  [m_motd_restore]="Restore default MOTD"
  [m_motd_preview]="Preview MOTD"
  [m_ssh]="SSH settings >"
  [m_ufw]="UFW firewall >"
  [m_fail2ban]="Fail2ban >"
  [m_hardening]="Kernel hardening"
  [m_docker]="Install Docker"
  [m_1panel]="Install 1Panel"
  [m_aliases]="Install shell aliases"
  [m_apt_clean]="APT cleanup"
  [m_cron]="Auto-reboot cron"
  [m_log]="Show action log"
  [m_scripts]="Scripts >"

  # ── SSH submenu ────────────────────────────────────────────────────────────
  [ssh_menu_title]="SSH Hardening"
  [ssh_m_status]="Status"
  [ssh_m_disable_pass]="Disable password auth"
  [ssh_m_restrict_root]="Restrict root login"
  [ssh_m_change_port]="Change SSH port"
  [ssh_status_title]="Current SSH settings"
  [ssh_port]="Port:"
  [ssh_pass_auth]="PasswordAuthentication:"
  [ssh_root_login]="PermitRootLogin:"
  [ssh_printlastlog]="PrintLastLog:"
  [ssh_disable_pass_warn]="This will lock out password-based SSH logins. Ensure you have a working SSH key."
  [ssh_disable_pass_confirm]="Disable password authentication?"
  [ssh_disable_pass_done]="Password authentication disabled. Key-based login only."
  [ssh_restrict_root_info]="Root can still log in with SSH keys; password login for root will be blocked."
  [ssh_restrict_root_done]="Root password login disabled (key-based root login still works)."
  [ssh_port_prompt]="New SSH port (1–65535):"
  [ssh_port_confirm]="Change SSH port to %s?"
  [ssh_port_done]="SSH port changed to %s. Reconnect on the new port."
  [ssh_port_ufw_added]="UFW rule for port %s/tcp added automatically."

  # ── UFW submenu ────────────────────────────────────────────────────────────
  [ufw_menu_title]="UFW Firewall"
  [ufw_m_status]="Status"
  [ufw_m_defaults]="Apply defaults (deny in / allow out)"
  [ufw_m_ssh]="Allow SSH (22/tcp)"
  [ufw_m_http]="Allow HTTP + HTTPS (80, 443)"
  [ufw_m_custom]="Allow custom port"
  [ufw_m_from_ip]="Allow from IP/CIDR"
  [ufw_m_delete]="Delete rule by number"
  [ufw_m_enable]="Enable UFW"
  [ufw_m_disable]="Disable UFW"
  [ufw_m_reset]="Reset UFW (removes all rules!)"
  [ufw_port_prompt]="Port (e.g. 8443):"
  [ufw_proto_prompt]="Protocol — tcp / udp / both (default: tcp):"
  [ufw_ip_prompt]="Source IP or CIDR (e.g. 1.2.3.4 or 1.2.3.0/24):"
  [ufw_port2_prompt]="Port to open (1–65535):"
  [ufw_delete_title]="Current UFW rules:"
  [ufw_delete_prompt]="Rule number to delete:"
  [ufw_delete_confirm]="Delete rule #%s?"
  [ufw_reset_confirm]="This will reset UFW and remove ALL rules. Continue?"
  [ufw_defaults_done]="Defaults applied: deny incoming / allow outgoing."

  # ── Fail2ban submenu ───────────────────────────────────────────────────────
  [f2b_menu_title]="Fail2ban"
  [f2b_m_install]="Install + enable"
  [f2b_m_jail]="Configure SSH jail"
  [f2b_m_status]="Status"
  [f2b_m_unban]="Unban IP"
  [f2b_not_installed]="Fail2ban not installed. Use 'Install + enable' first."
  [f2b_unban_prompt]="IP address to unban:"
  [f2b_done]="Fail2ban installed and enabled."
  [f2b_jail_done]="jail.local written and fail2ban restarted."
  [f2b_restart_failed]="Fail2ban restart failed. Ensure it is installed and enabled."

  # ── System ─────────────────────────────────────────────────────────────────
  [sys_updating]="Updating package lists..."
  [sys_upgrading]="Upgrading installed packages..."
  [sys_installing_base]="Installing base packages..."
  [sys_auto_updates_done]="Unattended upgrades enabled."
  [swap_exists]="Swap is already configured:"
  [swap_replace_confirm]="Replace existing swap?"
  [swap_size_prompt]="Swap size (e.g. 1G, 2G, 512M):"
  [swap_create_confirm]="Create %s swapfile at /swapfile?"
  [swap_fallocate_fail]="fallocate failed (btrfs?); falling back to dd..."
  [swap_done]="Swap configured: %s at /swapfile (swappiness=10)"
  [user_prompt]="New username:"
  [user_invalid]="Invalid username. Use lowercase letters, digits, underscores, hyphens (max 32 chars)."
  [user_exists]="User '%s' already exists."
  [user_confirm]="Create user '%s' and add to sudo?"
  [user_done]="User '%s' created and added to sudo."
  [user_ssh_key_prompt]="SSH public key for %s (leave blank to skip):"
  [user_ssh_key_invalid]="Invalid SSH public key format."
  [user_ssh_key_done]="SSH public key installed for '%s'."
  [alias_exists]="already exists, skipping."
  [alias_added]="added."
  [alias_reload_note]="NOTE: Run 'source ~/.bashrc' or reconnect via SSH to apply aliases."
  [apt_before]="Cache before cleanup: %s"
  [apt_after]="Cache after cleanup: %s"
  [cron_active]="Auto-reboot cron is currently active:"
  [cron_reconfigure]="Reconfigure?"
  [cron_disable_confirm]="Disable auto-reboot cron?"
  [cron_disabled]="Auto-reboot cron removed."
  [cron_install_confirm]="Install auto-reboot cron? (runs hourly, reboots only if kernel update pending)"
  [cron_done]="Auto-reboot cron installed."
  [hardening_exists]="Kernel hardening already applied."
  [hardening_reapply]="Re-apply / overwrite?"
  [hardening_done]="Kernel hardening applied."
  [full_setup_done]="Setup Complete"
  [full_setup_packages]="Packages updated:"
  [full_setup_base]="Base packages:"
  [full_setup_updates]="Auto-updates:"
  [full_setup_duration]="Duration:"

  # ── MOTD ───────────────────────────────────────────────────────────────────
  [motd_downloading]="Custom MOTD files not found locally; downloading..."
  [motd_installed]="Custom MOTD installed."
  [motd_restored]="Default MOTD restored."
  [motd_preview_title]="MOTD Preview"
  [motd_no_curl_wget]="Missing custom files and neither curl nor wget is available."

  # ── Log ────────────────────────────────────────────────────────────────────
  [log_empty]="No log file found."

  # ── Docker ─────────────────────────────────────────────────────────────────
  [docker_installed]="Docker is already installed: %s"
  [docker_reinstall]="Re-install anyway?"
  [docker_warn]="This will download and run the official Docker install script as root."
  [docker_sha256]="SHA256 of installer: %s"
  [docker_confirm]="Run Docker install script?"
  [docker_downloading]="Downloading Docker installer..."
  [docker_done]="Docker installed: %s"
  [1panel_warn]="This will download and run the 1Panel installer script as root."
  [1panel_confirm]="Run 1Panel install script?"
  [1panel_downloading]="Downloading 1Panel installer..."

  # ── Scripts submenu ────────────────────────────────────────────────────────
  [scripts_menu_title]="Utility Scripts"
  [scripts_m_cf]="Cloudflare DNS Manager"
  [scripts_m_bbr]="Enable TCP BBR"
  [scripts_downloading]="Script not found locally; downloading from GitHub..."
)

declare -A _RU
_RU=(
  [title]="Инструменты сервера MrCerber"
  [subtitle]="Ubuntu / Debian  |  Запуск от root"
  [select_lang]="Выберите язык"
  [confirm_yes]="Да"
  [confirm_no]="Нет"
  [press_enter]="Нажмите Enter для продолжения..."
  [back]="Назад"
  [exit]="Выход"
  [invalid_choice]="Неверный выбор."
  [cannot_be_empty]="Не может быть пустым."
  [done]="Готово."

  [err_backup_failed]="Ошибка резервной копии — прерывание."
  [err_download_failed]="Ошибка загрузки"
  [err_invalid_port]="Неверный порт. Должен быть от 1 до 65535."
  [err_invalid_ip]="Неверный формат IPv4 или CIDR."
  [err_invalid_size]="Неверный формат. Примеры: 1G, 2G, 512M"
  [err_sshd_invalid]="Конфиг sshd невалиден — резервная копия восстановлена."

  [os_not_ubuntu]="Скрипт предназначен для Ubuntu/Debian."
  [os_continue]="Продолжить всё равно?"
  [no_internet]="Нет подключения к интернету."

  [sec_quick]="Быстрая настройка"
  [sec_system]="Система"
  [sec_motd_ssh]="MOTD и SSH"
  [sec_security]="Безопасность"
  [sec_panels]="Панели"
  [sec_extras]="Дополнительно"
  [sec_scripts]="Скрипты"

  [m_alias]="Создать alias (mrc-tools)"
  [m_full_setup]="Полная установка"
  [m_update]="Обновить систему"
  [m_packages]="Установить базовые пакеты"
  [m_autoupdates]="Включить авто-обновления"
  [m_sudo_user]="Создать sudo пользователя"
  [m_swap]="Настроить swap"
  [m_motd_install]="Установить кастомный MOTD"
  [m_motd_restore]="Восстановить MOTD"
  [m_motd_preview]="Предпросмотр MOTD"
  [m_ssh]="Настройки SSH >"
  [m_ufw]="Фаервол UFW >"
  [m_fail2ban]="Fail2ban >"
  [m_hardening]="Харденинг ядра"
  [m_docker]="Установить Docker"
  [m_1panel]="Установить 1Panel"
  [m_aliases]="Установить aliases"
  [m_apt_clean]="Очистка APT"
  [m_cron]="Крон авто-перезагрузки"
  [m_log]="Показать лог"
  [m_scripts]="Скрипты >"

  [ssh_menu_title]="Настройки SSH"
  [ssh_m_status]="Статус"
  [ssh_m_disable_pass]="Отключить вход по паролю"
  [ssh_m_restrict_root]="Ограничить root-вход"
  [ssh_m_change_port]="Изменить порт SSH"
  [ssh_status_title]="Текущие настройки SSH"
  [ssh_port]="Порт:"
  [ssh_pass_auth]="Аутентификация по паролю:"
  [ssh_root_login]="Вход под root:"
  [ssh_printlastlog]="Вывод последнего входа:"
  [ssh_disable_pass_warn]="Это закроет вход по паролю. Убедитесь, что SSH-ключ уже настроен."
  [ssh_disable_pass_confirm]="Отключить аутентификацию по паролю?"
  [ssh_disable_pass_done]="Аутентификация по паролю отключена."
  [ssh_restrict_root_info]="Root сможет заходить по ключу, но не по паролю."
  [ssh_restrict_root_done]="Вход root по паролю запрещён (вход по ключу остаётся)."
  [ssh_port_prompt]="Новый порт SSH (1–65535):"
  [ssh_port_confirm]="Изменить порт SSH на %s?"
  [ssh_port_done]="Порт SSH изменён на %s. Переподключитесь по новому порту."
  [ssh_port_ufw_added]="Правило UFW для порта %s/tcp добавлено автоматически."

  [ufw_menu_title]="Фаервол UFW"
  [ufw_m_status]="Статус"
  [ufw_m_defaults]="Применить политики (запрет входящих / разрешение исходящих)"
  [ufw_m_ssh]="Разрешить SSH (22/tcp)"
  [ufw_m_http]="Разрешить HTTP + HTTPS (80, 443)"
  [ufw_m_custom]="Открыть произвольный порт"
  [ufw_m_from_ip]="Разрешить с IP/CIDR"
  [ufw_m_delete]="Удалить правило по номеру"
  [ufw_m_enable]="Включить UFW"
  [ufw_m_disable]="Выключить UFW"
  [ufw_m_reset]="Сбросить UFW (удалит все правила!)"
  [ufw_port_prompt]="Порт (например, 8443):"
  [ufw_proto_prompt]="Протокол — tcp / udp / both (по умолчанию: tcp):"
  [ufw_ip_prompt]="IP или CIDR источника (например, 1.2.3.4 или 1.2.3.0/24):"
  [ufw_port2_prompt]="Порт для открытия (1–65535):"
  [ufw_delete_title]="Текущие правила UFW:"
  [ufw_delete_prompt]="Номер правила для удаления:"
  [ufw_delete_confirm]="Удалить правило #%s?"
  [ufw_reset_confirm]="Это сбросит UFW и удалит ВСЕ правила. Продолжить?"
  [ufw_defaults_done]="Политики применены: запрет входящих / разрешение исходящих."

  [f2b_menu_title]="Fail2ban"
  [f2b_m_install]="Установить + включить"
  [f2b_m_jail]="Настроить SSH jail"
  [f2b_m_status]="Статус"
  [f2b_m_unban]="Разбанить IP"
  [f2b_not_installed]="Fail2ban не установлен. Сначала используйте 'Установить + включить'."
  [f2b_unban_prompt]="IP-адрес для разбана:"
  [f2b_done]="Fail2ban установлен и включён."
  [f2b_jail_done]="jail.local записан, fail2ban перезапущен."
  [f2b_restart_failed]="Перезапуск fail2ban не удался. Убедитесь, что он установлен."

  [sys_updating]="Обновление списков пакетов..."
  [sys_upgrading]="Обновление установленных пакетов..."
  [sys_installing_base]="Установка базовых пакетов..."
  [sys_auto_updates_done]="Авто-обновления включены."
  [swap_exists]="Swap уже настроен:"
  [swap_replace_confirm]="Заменить существующий swap?"
  [swap_size_prompt]="Размер swap (например, 1G, 2G, 512M):"
  [swap_create_confirm]="Создать swapfile размером %s в /swapfile?"
  [swap_fallocate_fail]="fallocate не сработал (btrfs?); используется dd..."
  [swap_done]="Swap настроен: %s в /swapfile (swappiness=10)"
  [user_prompt]="Имя нового пользователя:"
  [user_invalid]="Неверное имя. Допустимы: строчные буквы, цифры, подчёркивания, дефисы (макс. 32 символа)."
  [user_exists]="Пользователь '%s' уже существует."
  [user_confirm]="Создать пользователя '%s' и добавить в sudo?"
  [user_done]="Пользователь '%s' создан и добавлен в sudo."
  [user_ssh_key_prompt]="SSH публичный ключ для %s (оставьте пустым, чтобы пропустить):"
  [user_ssh_key_invalid]="Неверный формат SSH публичного ключа."
  [user_ssh_key_done]="SSH ключ установлен для '%s'."
  [alias_exists]="уже существует, пропускаю."
  [alias_added]="добавлен."
  [alias_reload_note]="ВАЖНО: Выполните 'source ~/.bashrc' или переподключитесь по SSH для применения."
  [apt_before]="Кэш до очистки: %s"
  [apt_after]="Кэш после очистки: %s"
  [cron_active]="Крон авто-перезагрузки активен:"
  [cron_reconfigure]="Перенастроить?"
  [cron_disable_confirm]="Отключить крон авто-перезагрузки?"
  [cron_disabled]="Крон авто-перезагрузки удалён."
  [cron_install_confirm]="Установить крон авто-перезагрузки? (запускается каждый час, перезагружает только при ожидающих обновлениях ядра)"
  [cron_done]="Крон авто-перезагрузки установлен."
  [hardening_exists]="Харденинг ядра уже применён."
  [hardening_reapply]="Применить заново / перезаписать?"
  [hardening_done]="Харденинг ядра применён."
  [full_setup_done]="Установка завершена"
  [full_setup_packages]="Пакеты обновлены:"
  [full_setup_base]="Базовые пакеты:"
  [full_setup_updates]="Авто-обновления:"
  [full_setup_duration]="Время:"

  [motd_downloading]="Файлы MOTD не найдены локально; загрузка..."
  [motd_installed]="Кастомный MOTD установлен."
  [motd_restored]="MOTD по умолчанию восстановлен."
  [motd_preview_title]="Предпросмотр MOTD"
  [motd_no_curl_wget]="Файлы MOTD отсутствуют, и нет curl или wget."

  [log_empty]="Файл лога не найден."

  [docker_installed]="Docker уже установлен: %s"
  [docker_reinstall]="Переустановить?"
  [docker_warn]="Будет скачан и выполнен официальный скрипт установки Docker от root."
  [docker_sha256]="SHA256 установщика: %s"
  [docker_confirm]="Запустить скрипт установки Docker?"
  [docker_downloading]="Скачивание установщика Docker..."
  [docker_done]="Docker установлен: %s"
  [1panel_warn]="Будет скачан и выполнен скрипт установки 1Panel от root."
  [1panel_confirm]="Запустить скрипт установки 1Panel?"
  [1panel_downloading]="Скачивание установщика 1Panel..."

  [scripts_menu_title]="Утилиты"
  [scripts_m_cf]="Cloudflare DNS Manager"
  [scripts_m_bbr]="Включить TCP BBR"
  [scripts_downloading]="Скрипт не найден локально; загрузка с GitHub..."
)

choose_language() {
  local lang
  lang=$(gum choose --header="Language / Язык" "English" "Русский") || lang="English"

  local -n _src
  if [[ "$lang" == "English" ]]; then
    _src=_EN
  else
    _src=_RU
  fi

  local k
  for k in "${!_src[@]}"; do
    T["$k"]="${_src[$k]}"
  done
}
